#!/bin/sh
#
# Start the xboxcontroller daemon....
#

case "$1" in
	start)
		/bin/./xboxcontroller ;;
	stop)
		killall xboxcontroller ;;
	restart) 
  	killall xboxcontroller 
		/bin/./xboxcontroller ;;
esac